### ISSUE TITLE
Crosshair position no longer centered with latest NVidia Drivers

### ISSUE THREAD

**Issue by drivera73** [tgienger/Ultimate-Crosshair#3]
With NVidia drivers up to 376.48 everything works fine, but with 378.49 the crosshairs are no longer centered on a 1440p display.

**Comment by tgienger** [comment]
That's interesting, though I believe it's a driver issues for the moment and nothing I can personally do to fix it. I had to revert off of 378.49 for other issues, a game I'm working on wouldn't load in the dev environment.

Also I'm not actively using or updating this. Anyone is welcome to fork it and make changes. Perhaps someday!

**Comment by drivera73** [comment]
The issue was apparently fixed by clearing out the "window size" cache information stored in Overwolf.  Is there an easy(ish) way to add a button to reset that setting? I.e. "recalculate screen size" so that if there's need to reset that one need not dig through configurations?

**Comment by ghost** [comment]
@drivera73 Can you help me fix this? I love this overlay and would like it functional again :)

**Comment by ghost** [comment]
"clearing out the window size cache information"
wat

**Comment by ghost** [comment]
Any update on how to fix this?

**Comment by drivera73** [comment]
What I did was go into %localappdata%\Overwolf\Settings\SettingsPageODK.xml and remove the entries for the application in the WindowsPropertiesSettings.  You'll need to figure out the application ID (some weird lettery thing like gkohfnaflcefoanolhceophmeeajblhjedlgddil) and remove the entries for the application.

Naturally, Overwolf must be turned off.  When you turn it off the crosshair _**should**_ be in the right place.  The controls could be kinda out of whack, but at least the crosshair will be properly positioned.

Cheers!

**Comment by ghost** [comment]
thanks ^>^

**Comment by MentalMilkshake** [comment]
This didn't work at all still not centered @_@

**Comment by Myrran** [comment]
Doesn't work for me eather. Maybe I'm doing it wrong because the instructions are unclear.

**Comment by thadawilliams** [comment]
Before I tried to fix it, it was only a little bit too high. Now, after trying to fix it, it's WAY off and I can't seem to get it even close. 

I use this every day. I really could use some help getting this right.

**Comment by Myrran** [comment]
I heard that u can use a crosshair in Recursion. Is it correct?

**Comment by MentalMilkshake** [comment]
seriously this is annoying has anyone figured out how to fix the not centered issue?

**Comment by drivera73** [comment]
1. Turn off (exit) Overwolf
2. Open %localappdata%\Overwolf\Settings\SettingsPageODK.xml in a DECENT text editor (Notepad not recommended, try Notepad++ - Google is your friend :) )
3. Find the <PropertyNameValue> section that deals with "WindowPropertiesSettings"
`<Value Internal_Type="List" List_Type="WindowsPropertiesSettings">`
4. Remove (or comment out) all <WindowsPropertiesSettings> elements inside that block
5. Re-start Overwolf and Ultimate Crosshair

If this does NOT work (possible), then...

1. Turn off (exit) Overwolf
2. Open %localappdata%\Overwolf\Settings\SettingsPageODK.xml in a DECENT text editor (see point 2, above)
3. Find the <PropertyNameValue> section that deals with "WindowPropertiesSettings"
`<Value Internal_Type="List" List_Type="WindowsPropertiesSettings">`
4. Modify the correct <WindowsPropertiesSettings> element for Ultimate Crosshair to contain the proper Width and Height values for your screen resolution.  It'll have a values of WindowId similar to Window_Extension_gkohfnaflcefoanolhceophmeeajblhjedlgddil (there will be a 2nd one *that you must not touch* called {WindowId}_CrossWindow - where {windowId} is the aforementioned value).  So, for instance, if the correct WindowId value were ABCDE, you'd have an entry with WindowId=ABCDE, and another one with WindowID=ABCDE_CrossWindow - that's how you can verify that ABCDE is the correct WindowId value and you're not messing with the wrong crap.  In my case I set the resolution values to Width=2560 and Height=1440 (for 1440p).  Other likely values are W=1920 H=1080 (1080p), W=3840 H=2160 (4K).  You'll need to figure this out on your own.
5. Re-start Overwolf and Ultimate Crosshair

If you want the exact WindowId, I think it's listed in the extension installation screen where you can verify that Ulitmate Crosshair is installed.

**Comment by ghost** [comment]
DING DING DING we have a winner @drivera73 . Thanks pal. Great write up.

**Comment by ghost** [comment]
Also do we he have to compile to get the opk now?

**Comment by drivera73** [comment]
No. These changes are all intended to be made after deployment. I haven't looked into how to rebuild the extension package, nor how one would go about generating a permanent fix for this that doesn't require this meddling.

**Comment by Myrran** [comment]
I followed drivera's instructions and it worked! Drivera, thank you very much!

**Comment by MentalMilkshake** [comment]
No idea what I am doing wrong but I tried it and it didn't fix it :/

**Comment by MentalMilkshake** [comment]
When I open it it will be centered then it jumps up and to the left

**Comment by Myrran** [comment]
It definetely stays centered for me. I used the second method. I even put a thumbs up to @drivera73 post for what it's worth.

**Comment by djgoosebucket** [comment]
i put in the correct resolution and it moves the settings for ultimate crosshair but the actual crosshair is in the same place (not centered). help would be greatly appreciated thx

**Comment by Polyrhythm34** [comment]
Yo, my mis-alignment issue was simple.  Make sure you don't have your screen zoomed in or out. press control and scroll wheel till setting are at 100% or right click, display settings, Scale and layout (Change the size of text, apps, blahblhah) set to 100%.

**Comment by drivera73** [comment]
Tool is no longer supported or maintained.
